# Path of the CSV file containing the exam schedule for a particular semester
in_file = "exam_data.csv"

# Path of the output calendar file
out_file = "out/schedule.ics"

# Location of the university
location = "5 Allée Antonio Machado, 31058 Toulouse, France"

# IANA timezone code
timezone = "Europe/Paris"

# Subject codes (as a list of strings)
subject_codes = []
